export const songs = [
  {
    id: 1,
    album: "Parachutes",
    song: "Don’t Panic",
    year: "2000",
    songLenth: "2:17",
    NumberAlbum: 1,
  },
  {
    id: 2,
    album: "Parachutes",
    song: "Shiver",
    year: "2000",
    songLenth: "4:59",
    NumberAlbum: 2,
  },
  {
    id: 3,
    album: "Parachutes",
    song: "Spies",
    year: "2000",
    songLenth: "5:18",
    NumberAlbum: 3,
  },
  {
    id: 4,
    album: "Parachutes",
    song: "Sparks",
    year: "2000",
    songLenth: "3:47",
    NumberAlbum: 4,
  },
  {
    id: 5,
    album: "Parachutes",
    song: "Yellow",
    year: "2000",
    songLenth: "4:29",
    NumberAlbum: 5,
  },
  {
    id: 6,
    album: "Parachutes",
    song: "Trouble",
    year: "2000",
    songLenth: "4:30",
    NumberAlbum: 6,
  },
  {
    id: 7,
    album: "Parachutes",
    song: "Parachutes",
    year: "2000",
    songLenth: "0:46",
    NumberAlbum: 7,
  },
  {
    id: 8,
    album: "Parachutes",
    song: "High Speed",
    year: "2000",
    songLenth: "4:14",
    NumberAlbum: 8,
  },
  {
    id: 9,
    album: "Parachutes",
    song: "We Never Change",
    year: "2000",
    songLenth: "4:09",
    NumberAlbum: 9,
  },
  {
    id: 10,
    album: "Parachutes",
    song: "Everything's Not Lost",
    year: "2000",
    songLenth: "4:09",
    NumberAlbum: 9,
  },
  {
    id: 11,
    album: "A Rush of Blood to the Head",
    song: "Politik",
    year: "2002",
    songLenth: "5:18",
    NumberAlbum: 1,
  },
  {
    id: 12,
    album: "A Rush of Blood to the Head",
    song: "In My Place",
    year: "2002",
    songLenth: "3:48",
    NumberAlbum: 2,
  },
  {
    id: 13,
    album: "A Rush of Blood to the Head",
    song: "God Put a Smile upon Your Face",
    year: "2002",
    songLenth: "4:57",
    NumberAlbum: 3,
  },
  {
    id: 14,
    album: "A Rush of Blood to the Head",
    song: "The Scientist",
    year: "2002",
    songLenth: "5:09",
    NumberAlbum: 4,
  },
  {
    id: 15,
    album: "A Rush of Blood to the Head",
    song: "Clocks",
    year: "2002",
    songLenth: "5:07",
    NumberAlbum: 5,
  },
  {
    id: 16,
    album: "A Rush of Blood to the Head",
    song: "Daylight",
    year: "2002",
    songLenth: "5:27",
    NumberAlbum: 6,
  },
  {
    id: 17,
    album: "A Rush of Blood to the Head",
    song: "Green Eyes",
    year: "2002",
    songLenth: "3:43",
    NumberAlbum: 7,
  },
  {
    id: 18,
    album: "A Rush of Blood to the Head",
    song: "Warning Sign",
    year: "2002",
    songLenth: "5:31",
    NumberAlbum: 8,
  },
  {
    id: 19,
    album: "A Rush of Blood to the Head",
    song: "A Whisper",
    year: "2002",
    songLenth: "3:58",
    NumberAlbum: 9,
  },
  {
    id: 20,
    album: "A Rush of Blood to the Head",
    song: "A Rush of Blood to the Head",
    year: "2002",
    songLenth: "3:58",
    NumberAlbum: 10,
  },
  {
    id: 21,
    album: "A Rush of Blood to the Head",
    song: "Amsterdam",
    year: "2002",
    songLenth: "no info",
    NumberAlbum: 11,
  },
  {
    id: 22,
    album: "X&Y",
    song: "Square One",
    year: "2005",
    songLenth: "4:47",
    NumberAlbum: 1,
  },
  {
    id: 23,
    album: "X&Y",
    song: "What If",
    year: "2005",
    songLenth: "4:57",
    NumberAlbum: 2,
  },
  {
    id: 24,
    album: "X&Y",
    song: "White Shadows",
    year: "2005",
    songLenth: "5:28",
    NumberAlbum: 3,
  },
  {
    id: 25,
    album: "X&Y",
    song: "Fix You",
    year: "2005",
    songLenth: "4:54",
    NumberAlbum: 4,
  },
  {
    id: 26,
    album: "X&Y",
    song: "Talk",
    year: "2005",
    songLenth: "5:11",
    NumberAlbum: 5,
  },
  {
    id: 27,
    album: "X&Y",
    song: "X&Y",
    year: "2005",
    songLenth: "4:34",
    NumberAlbum: 6,
  },
  {
    id: 28,
    album: "X&Y",
    song: "Speed of Sound",
    year: "2005",
    songLenth: "4:48",
    NumberAlbum: 7,
  },
  {
    id: 29,
    album: "X&Y",
    song: "A Message",
    year: "2005",
    songLenth: "4:45",
    NumberAlbum: 8,
  },
  {
    id: 30,
    album: "X&Y",
    song: "Low",
    year: "2005",
    songLenth: "5:32",
    NumberAlbum: 9,
  },
  {
    id: 30,
    album: "X&Y",
    song: "The Hardest Part",
    year: "2005",
    songLenth: "4:25",
    NumberAlbum: 10,
  },
  {
    id: 31,
    album: "X&Y",
    song: "Swallowed in the Sea",
    year: "2005",
    songLenth: "3:58",
    NumberAlbum: 11,
  },
  {
    id: 32,
    album: "X&Y",
    song: "Twisted Logic",
    year: "2005",
    songLenth: "5:01",
    NumberAlbum: 12,
  },
  {
    id: 33,
    album: "X&Y",
    song: "'Til Kingdom Come",
    year: "2005",
    songLenth: "4:10",
    NumberAlbum: 13,
  },
  {
    id: 34,
    album: "Viva la Vida or Death and All His Friends",
    song: "Life in Technicolor",
    year: "2008",
    songLenth: "2:29",
    NumberAlbum: 1,
  },
  {
    id: 35,
    album: "Viva la Vida or Death and All His Friends",
    song: "Cemeteries of London",
    year: "2008",
    songLenth: "3:21",
    NumberAlbum: 2,
  },
  {
    id: 35,
    album: "Viva la Vida or Death and All His Friends",
    song: "Lost!",
    year: "2008",
    songLenth: "3:55",
    NumberAlbum: 3,
  },
  {
    id: 36,
    album: "Viva la Vida or Death and All His Friends",
    song: "42",
    year: "2008",
    songLenth: "3:57",
    NumberAlbum: 4,
  },
  {
    id: 37,
    album: "Viva la Vida or Death and All His Friends",
    song: "Lovers in Japan / Reign of Love",
    year: "2008",
    songLenth: "6:51",
    NumberAlbum: 5,
  },
  {
    id: 37,
    album: "Viva la Vida or Death and All His Friends",
    song: "Yes",
    year: "2008",
    songLenth: "7:06",
    NumberAlbum: 6,
  },
  {
    id: 38,
    album: "Viva la Vida or Death and All His Friends",
    song: "Viva la Vida",
    year: "2008",
    songLenth: "4:01",
    NumberAlbum: 7,
  },
  {
    id: 39,
    album: "Viva la Vida or Death and All His Friends",
    song: "Violet Hill",
    year: "2008",
    songLenth: "3:42",
    NumberAlbum: 8,
  },
  {
    id: 40,
    album: "Viva la Vida or Death and All His Friends",
    song: "Strawberry Swing",
    year: "2008",
    songLenth: "4:09",
    NumberAlbum: 9,
  },
  {
    id: 41,
    album: "Viva la Vida or Death and All His Friends",
    song: "Death and All His Friends",
    year: "2008",
    songLenth: "6:18",
    NumberAlbum: 10,
  },
  {
    id: 42,
    album: "Mylo Xyloto",
    song: "Mylo Xyloto",
    year: "2011",
    songLenth: "0:42",
    NumberAlbum: 1,
  },
  {
    id: 43,
    album: "Mylo Xyloto",
    song: "Hurts Like Heaven",
    year: "2011",
    songLenth: "4:02",
    NumberAlbum: 2,
  },
  {
    id: 44,
    album: "Mylo Xyloto",
    song: "Paradise",
    year: "2011",
    songLenth: "4:38",
    NumberAlbum: 3,
  },
  {
    id: 45,
    album: "Mylo Xyloto",
    song: "Charlie Brown",
    year: "2011",
    songLenth: "4:45",
    NumberAlbum: 4,
  },
  {
    id: 46,
    album: "Mylo Xyloto",
    song: "Us Against the World",
    year: "2011",
    songLenth: "4:00",
    NumberAlbum: 5,
  },
  {
    id: 47,
    album: "Mylo Xyloto",
    song: "M.M.I.X.",
    year: "2011",
    songLenth: "0:48",
    NumberAlbum: 6,
  },
  {
    id: 48,
    album: "Mylo Xyloto",
    song: "Every Teardrop Is a Waterfall",
    year: "2011",
    songLenth: "4:01",
    NumberAlbum: 7,
  },
  {
    id: 48,
    album: "Mylo Xyloto",
    song: "Major Minus",
    year: "2011",
    songLenth: "3:30",
    NumberAlbum: 8,
  },
  {
    id: 49,
    album: "Mylo Xyloto",
    song: "U.F.O.",
    year: "2011",
    songLenth: "2:18",
    NumberAlbum: 9,
  },
  {
    id: 49,
    album: "Mylo Xyloto",
    song: "Princess of China",
    year: "2011",
    songLenth: "3:58",
    NumberAlbum: 10,
  },
  {
    id: 50,
    album: "Mylo Xyloto",
    song: "Up in Flames",
    year: "2011",
    songLenth: "3:13",
    NumberAlbum: 11,
  },
  {
    id: 51,
    album: "Mylo Xyloto",
    song: "A Hopeful Transmission",
    year: "2011",
    songLenth: "0:33",
    NumberAlbum: 12,
  },
  {
    id: 51,
    album: "Mylo Xyloto",
    song: "Don't Let It Break Your Heart",
    year: "2011",
    songLenth: "3:54",
    NumberAlbum: 13,
  },
  {
    id: 52,
    album: "Mylo Xyloto",
    song: "Up with the Birds",
    year: "2011",
    songLenth: "3:46",
    NumberAlbum: 14,
  },
  {
    id: 53,
    album: "Ghost Stories",
    song: "Always in My Head",
    year: "2011",
    songLenth: "3:36",
    NumberAlbum: 1,
  },
  {
    id: 54,
    album: "Ghost Stories",
    song: "Magic",
    year: "2014",
    songLenth: "4:45",
    NumberAlbum: 2,
  },
  {
    id: 55,
    album: "Ghost Stories",
    song: "Ink",
    year: "2014",
    songLenth: "3:48",
    NumberAlbum: 3,
  },
  {
    id: 56,
    album: "Ghost Stories",
    song: "True Love",
    year: "2014",
    songLenth: "4:05",
    NumberAlbum: 4,
  },
  {
    id: 57,
    album: "Ghost Stories",
    song: "Midnight",
    year: "2014",
    songLenth: "4:54",
    NumberAlbum: 5,
  },
  {
    id: 58,
    album: "Ghost Stories",
    song: "Another’s Arms",
    year: "2014",
    songLenth: "3:54",
    NumberAlbum: 6,
  },
  {
    id: 59,
    album: "Ghost Stories",
    song: "Oceans",
    year: "2014",
    songLenth: "5:21",
    NumberAlbum: 7,
  },
  {
    id: 60,
    album: "Ghost Stories",
    song: "A Sky Full of Stars",
    year: "2014",
    songLenth: "4:28",
    NumberAlbum: 8,
  },
  {
    id: 61,
    album: "Ghost Stories",
    song: "O",
    year: "2014",
    songLenth: "7:47",
    NumberAlbum: 9,
  },
  {
    id: 62,
    album: "A Head Full of Dreams",
    song: "A Head Full of Dreams",
    year: "2015",
    songLenth: "3:43",
    NumberAlbum: 1,
  },
  {
    id: 62,
    album: "A Head Full of Dreams",
    song: "Birds",
    year: "2015",
    songLenth: "3:49",
    NumberAlbum: 2,
  },
  {
    id: 63,
    album: "A Head Full of Dreams",
    song: "Hymn for the Weekend",
    year: "2015",
    songLenth: "4:18",
    NumberAlbum: 3,
  },
  {
    id: 64,
    album: "A Head Full of Dreams",
    song: "Everglow",
    year: "2015",
    songLenth: "4:42",
    NumberAlbum: 4,
  },
  {
    id: 65,
    album: "A Head Full of Dreams",
    song: "Adventure of a Lifetime",
    year: "2015",
    songLenth: "4:23",
    NumberAlbum: 5,
  },
  {
    id: 66,
    album: "A Head Full of Dreams",
    song: "Fun",
    year: "2015",
    songLenth: "4:27",
    NumberAlbum: 6,
  },
  {
    id: 67,
    album: "A Head Full of Dreams",
    song: "Kaleidoscope",
    year: "2015",
    songLenth: "1:51",
    NumberAlbum: 7,
  },
  {
    id: 68,
    album: "A Head Full of Dreams",
    song: "Army of One",
    year: "2015",
    songLenth: "6:16",
    NumberAlbum: 8,
  },
  {
    id: 69,
    album: "A Head Full of Dreams",
    song: "Amazing Day",
    year: "2015",
    songLenth: "4:31",
    NumberAlbum: 9,
  },
  {
    id: 70,
    album: "A Head Full of Dreams",
    song: "Colour Spectrum",
    year: "2015",
    songLenth: "1:00",
    NumberAlbum: 10,
  },
  {
    id: 71,
    album: "A Head Full of Dreams",
    song: "Up&Up",
    year: "2015",
    songLenth: "6:45",
    NumberAlbum: 11,
  },
  {
    id: 72,
    album: "Everyday Life (Sunrise)",
    song: "Sunrise",
    year: "2019",
    songLenth: "2:31",
    NumberAlbum: 1,
  },
  {
    id: 73,
    album: "Everyday Life (Sunrise)",
    song: "Church",
    year: "2019",
    songLenth: "3:50",
    NumberAlbum: 2,
  },
  {
    id: 74,
    album: "Everyday Life (Sunrise)",
    song: "Trouble in Town",
    year: "2019",
    songLenth: "4:38",
    NumberAlbum: 3,
  },
  {
    id: 75,
    album: "Everyday Life (Sunrise)",
    song: "Broken",
    year: "2019",
    songLenth: "2:30",
    NumberAlbum: 4,
  },
  {
    id: 76,
    album: "Everyday Life (Sunrise)",
    song: "Daddy",
    year: "2019",
    songLenth: "4:58",
    NumberAlbum: 5,
  },
  {
    id: 77,
    album: "Everyday Life (Sunrise)",
    song: "WOTW / POTP",
    year: "2019",
    songLenth: "1:16",
    NumberAlbum: 6,
  },
  {
    id: 78,
    album: "Everyday Life (Sunrise)",
    song: "Arabesque",
    year: "2019",
    songLenth: "5:40",
    NumberAlbum: 7,
  },
  {
    id: 79,
    album: "Everyday Life (Sunrise)",
    song: "ArabeWhen I Need a Friendsque",
    year: "2019",
    songLenth: "2:35",
    NumberAlbum: 8,
  },
  {
    id: 80,
    album: "Everyday Life (Sunset)",
    song: "Guns",
    year: "2019",
    songLenth: "1:55",
    NumberAlbum: 1,
  },
  {
    id: 81,
    album: "Everyday Life (Sunset)",
    song: "Orphans",
    year: "2019",
    songLenth: "3:17",
    NumberAlbum: 2,
  },
  {
    id: 82,
    album: "Everyday Life (Sunset)",
    song: "Èkó",
    year: "2019",
    songLenth: "2:37",
    NumberAlbum: 3,
  },
  {
    id: 83,
    album: "Everyday Life (Sunset)",
    song: "Cry Cry Cry",
    year: "2019",
    songLenth: "2:47",
    NumberAlbum: 4,
  },
  {
    id: 84,
    album: "Everyday Life (Sunset)",
    song: "Old Friends",
    year: "2019",
    songLenth: "2:26",
    NumberAlbum: 5,
  },
  {
    id: 85,
    album: "Everyday Life (Sunset)",
    song: "بنی آدم",
    year: "2019",
    songLenth: "3:14",
    NumberAlbum: 6,
  },
  {
    id: 86,
    album: "Everyday Life (Sunset)",
    song: "Champion of the World",
    year: "2019",
    songLenth: "4:17",
    NumberAlbum: 7,
  },
  {
    id: 87,
    album: "Everyday Life (Sunset)",
    song: "Everyday Life",
    year: "2019",
    songLenth: "4:18",
    NumberAlbum: 8,
  },
  {
    id: 88,
    album: "Music of the Spheres",
    song: "Music of the Spheres",
    year: "2019",
    songLenth: "0:53",
    NumberAlbum: 1,
  },
  {
    id: 89,
    album: "Music of the Spheres",
    song: "Higher Power",
    year: "2019",
    songLenth: "3:26",
    NumberAlbum: 2,
  },
  {
    id: 90,
    album: "Music of the Spheres",
    song: "Humankind",
    year: "2019",
    songLenth: "4:26",
    NumberAlbum: 3,
  },
  {
    id: 91,
    album: "Music of the Spheres",
    song: "Alien Choir",
    year: "2019",
    songLenth: "0:53",
    NumberAlbum: 4,
  },
  {
    id: 92,
    album: "Music of the Spheres",
    song: "Let Somebody Go",
    year: "2019",
    songLenth: "4:01",
    NumberAlbum: 5,
  },
  {
    id: 93,
    album: "Music of the Spheres",
    song: "Human Heart",
    year: "2019",
    songLenth: "3:08",
    NumberAlbum: 6,
  },
  {
    id: 94,
    album: "Music of the Spheres",
    song: "People of the Pride",
    year: "2019",
    songLenth: "3:37",
    NumberAlbum: 7,
  },
  {
    id: 95,
    album: "Music of the Spheres",
    song: "Biutyful",
    year: "2019",
    songLenth: "3:12",
    NumberAlbum: 8,
  },
  {
    id: 96,
    album: "Music of the Spheres",
    song: "Music of the Spheres II",
    year: "2019",
    songLenth: "0:21",
    NumberAlbum: 9,
  },
  {
    id: 97,
    album: "Music of the Spheres",
    song: "My Universe",
    year: "2019",
    songLenth: "3:46",
    NumberAlbum: 10,
  },
  {
    id: 98,
    album: "Music of the Spheres",
    song: "Infinity Sign",
    year: "2019",
    songLenth: "3:46",
    NumberAlbum: 11,
  },
  {
    id: 99,
    album: "Music of the Spheres",
    song: "Infinity Sign",
    year: "2019",
    songLenth: "10:18",
    NumberAlbum: 12,
  },
];
