export const array = ['42',
'a message',
'a rush of blood to the head',
'a warning sign',
'a whisper',
'amsterdam',
'atlas',
'brothers and sisters',
'brothers and sisters',
'cemeteries of london',
'charlie brown',
'chinese sleep chant',
'clocks',
'daylight',
'death and all his friends',
'don’t let it break your heart',
'don’t panic',
'easy to please',
'every teardrop is a waterfall',
'everything’s not lost',
'fix you',
'glass of water',
'god put a smile upon your face',
'green eyes',
'high speed',
'hurts like heaven',
'in my place',
'life in technicolor ii',
'lost!',
'lovers in japan',
'lovers in japan / reign of love',
'low',
'major minus',
'm.m.i.x.',
'no more keeping my feet on the ground',
'only superstition',
'parachutes',
'paradise',
'politik',
'princess of china',
'proof',
'prospekt’s march / poppyfields',
'rainy day',
'see you soon',
'shiver',
'sparks',
'speed of sound',
'square one',
'strawberry swing',
'swallowed in the sea',
'talk',
'the escapist',
'the ground',
'the hardest part',
'the scientist',
'til kingdom come',
'till kingdom come',
'trouble',
'twisted logic',
'ufo',
'up in flames',
'up with the birds',
'us against the world',
'Violet hill',
'Viva la vida',
'warning sign',
'we never change',
'what if',
'white shadows',
'x and y',
'x&y',
'yellow',
'yes'];